# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 569)
        MainWindow.setStyleSheet("background-color: rgb(81, 81, 94);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("background-color: rgb(81, 81, 94);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Segoe UI Semibold\";")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setStyleSheet(" border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(1, 1, 1, 30);\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet(" border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 83);\n"
"border-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 6, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(71, 71, 83);\n"
"border-radius: 20px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(84, 84, 91);\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 7, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet(" border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 83);\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 83);\n"
"border-radius: 20px;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 3, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 83);\n"
"border-radius: 20px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setStyleSheet(" border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 83);\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 4, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setStyleSheet(" border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(1, 1, 1, 30);\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Текст в аудио"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введите текст для конвертации"))
        self.pushButton_3.setText(_translate("MainWindow", "Скачать"))
        self.comboBox.setItemText(0, _translate("MainWindow", "48000"))
        self.comboBox.setItemText(1, _translate("MainWindow", "8000"))
        self.comboBox.setItemText(2, _translate("MainWindow", "24000"))
        self.pushButton_4.setText(_translate("MainWindow", "Конвертировать"))
        self.label_2.setText(_translate("MainWindow", "Голос"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Стандартаная"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Premium👑"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Иван"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Ирина"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Александра"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Случайный"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Atutum 👑"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Алексей 👑"))
        self.label.setText(_translate("MainWindow", "Тон"))
        self.label_4.setText(_translate("MainWindow", "Скорость Convertil"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Premium/premium — small.png\"/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Применить"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Ввести лицензионный ключ"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
